env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
      - .tsx
  import/extensions:
    - error
    - never
  react/function-component-definition:
    - error
    - namedComponents: function-declaration
      unnamedComponents: function-expression
  react/react-in-jsx-scope: 'off'
  import/prefer-default-export: 'off'
