FROM rust:1.58

WORKDIR /opt/myself

RUN rustc --version
RUN rustup target add wasm32-unknown-unknown
RUN cargo install --locked trunk
RUN cargo install --locked wasm-bindgen-cli

RUN mkdir src && echo "fn main() {}" > src/main.rs

COPY Cargo.toml Cargo.lock ./

RUN cargo fetch --locked

COPY . ./

EXPOSE 8080
CMD trunk serve
